# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake on a single platform

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  CONAN_USER_HOME: "${{ github.workspace }}/release/"
  CONAN_USER_HOME_SHORT: "${{ github.workspace }}/release/short"

jobs:
  build-and-test:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt-get install -y build-essential cmake ninja-build

    - name: Setup vcpkg (it does not install any package yet)
      uses: lukka/run-vcpkg@v11
      env:
        VCPKG_DEFAULT_TRIPLET: x64-linux-dynamic
        VCPKG_OVERLAY_TRIPLETS: ${{github.workspace}}/custom-triplets
      with:
        vcpkgGitCommitId: '3b7578831da081ba164be30da8d9382a64841059'
        runVcpkgInstall: true

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: |
        cmake -B ${{github.workspace}}/build --preset "linux-release" -DVCPKG_TARGET_TRIPLET=x64-linux-dynamic

    - name: Build
      # Build your program with the given configuration
      run:
        cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Run tests
      run:
        y/build/EdgeLinkTests

    #- name: Package
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
    #  run:
    #    cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target package